import { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Plus, FileText, Sparkles, Tag, Star, Trash2,
  Edit3, Search, Pin, FileUp, Youtube, Globe,
  Mic, Check, X, BookOpen, Wand2, Copy,
  Download, AlertCircle, Loader2
} from 'lucide-react';
import { supabase } from '../../lib/supabase';
import { Note } from '../../lib/supabase';

const NOTE_TYPES = [
  { value: 'long', label: 'Long Notes' },
  { value: 'short', label: 'Short Notes' },
  { value: 'bullet', label: 'Bullet Points' },
  { value: 'flashcard', label: 'Flashcards' },
  { value: 'revision', label: 'Revision Sheet' },
  { value: 'cheatsheet', label: 'Cheat Sheet' },
  { value: 'formula', label: 'Formula Sheet' },
  { value: 'mindmap', label: 'Mind Map' },
];

const SOURCE_TYPES = [
  { value: 'manual', label: 'Write manually', icon: Edit3 },
  { value: 'pdf', label: 'From PDF', icon: FileUp },
  { value: 'youtube', label: 'YouTube URL', icon: Youtube },
  { value: 'website', label: 'Website URL', icon: Globe },
  { value: 'audio', label: 'Audio Recording', icon: Mic },
];

const SUBJECTS = ['Mathematics', 'Physics', 'Chemistry', 'Biology', 'Computer Science', 'History', 'English', 'Economics'];

function generateNoteContent(topic: string, noteType: string, subject: string): string {
  const t = topic.trim() || 'the topic';
  const s = subject || 'General Studies';

  switch (noteType) {
    case 'short':
      return `# ${t} — Short Notes

**Subject:** ${s}

## Key Points

- **Definition:** ${t} refers to the fundamental concepts and principles in ${s}.
- **Core Idea:** Understanding ${t} requires grasping both theoretical foundations and practical applications.
- **Importance:** ${t} is essential for building advanced knowledge in ${s}.
- **Application:** Used in real-world scenarios within ${s} and related fields.

## Quick Summary

${t} encompasses several key concepts that form the foundation of ${s}. Mastering these concepts enables deeper understanding and practical problem-solving.

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;

    case 'bullet':
      return `# ${t} — Bullet Points

**Subject:** ${s}

## Main Concepts

- Definition and scope of ${t}
- Key principles underlying ${t}
- Historical context and development
- Modern applications and relevance
- Common misconceptions about ${t}
- Relationship to other topics in ${s}
- Practical examples and case studies
- Important formulas or equations (if applicable)
- Key terminology and definitions
- Recommended further reading

## Key Terms

- **Term 1:** Core concept related to ${t}
- **Term 2:** Important principle in ${t}
- **Term 3:** Application of ${t} in practice

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;

    case 'flashcard':
      return `# ${t} — Flashcards

**Subject:** ${s}

## Card 1
**Q:** What is ${t}?
**A:** ${t} is a fundamental concept in ${s} that describes key principles and their applications.

## Card 2
**Q:** Why is ${t} important?
**A:** Understanding ${t} is crucial for mastering ${s} and applying knowledge to real-world problems.

## Card 3
**Q:** What are the key components of ${t}?
**A:** The main components include theoretical foundations, practical methods, and real-world applications.

## Card 4
**Q:** How is ${t} applied in practice?
**A:** ${t} is applied through systematic analysis, problem-solving techniques, and evidence-based methods.

## Card 5
**Q:** What are common challenges in learning ${t}?
**A:** Common challenges include grasping abstract concepts, connecting theory to practice, and mastering terminology.

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;

    case 'revision':
      return `# ${t} — Revision Sheet

**Subject:** ${s} | **Date:** ${new Date().toLocaleDateString()}

## Must-Know Concepts

1. **Core Definition:** ${t} — fundamental concept in ${s}
2. **Key Principles:** The underlying rules and theories governing ${t}
3. **Important Formulas:** Mathematical or logical expressions related to ${t}
4. **Applications:** How ${t} is used in practice
5. **Common Pitfalls:** Mistakes to avoid when working with ${t}

## Quick Review Questions

- [ ] Can you define ${t} in your own words?
- [ ] Can you list 3 key principles of ${t}?
- [ ] Can you give 2 real-world examples?
- [ ] Can you solve basic problems related to ${t}?

## Memory Aids

- **Mnemonic 1:** Create an acronym from key terms
- **Visual Aid:** Draw a concept map connecting ideas
- **Practice:** Solve 5 problems related to ${t}

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;

    case 'cheatsheet':
      return `# ${t} — Cheat Sheet

**Subject:** ${s}

## Quick Reference

| Concept | Description |
|---------|-------------|
| Definition | ${t} in ${s} |
| Key Formula | f(x) = ... (subject-specific) |
| Unit/Type | Depends on context |
| Range | Application-dependent |

## Essential Rules

1. **Rule 1:** Fundamental principle of ${t}
2. **Rule 2:** Key relationship in ${t}
3. **Rule 3:** Common property of ${t}

## Do's and Don'ts

- ✅ Do: Understand the underlying theory
- ✅ Do: Practice with varied examples
- ❌ Don't: Memorize without understanding
- ❌ Don't: Skip foundational concepts

## Common Values

| Item | Value |
|------|-------|
| Standard constant | Reference value |
| Common parameter | Typical range |

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;

    case 'formula':
      return `# ${t} — Formula Sheet

**Subject:** ${s}

## Core Formulas

1. **Basic Formula:**
   $$F = ma$$
   *Fundamental relationship in ${t}*

2. **Derived Formula:**
   $$E = \\frac{1}{2}mv^2$$
   *Energy expression related to ${t}*

3. **Advanced Formula:**
   $$\\nabla \\cdot \\vec{F} = \\rho$$
   *Differential form for ${t}*

## Key Equations

| Formula | Description | When to Use |
|---------|-------------|-------------|
| F = ma | Newton's second law | Force calculations |
| E = mc² | Mass-energy equivalence | Energy problems |
| PV = nRT | Ideal gas law | Thermodynamics |

## Units and Conversions

- **SI Unit:** Standard measurement unit
- **CGS Unit:** Alternative unit system
- **Conversion:** 1 unit = X alternative units

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;

    case 'mindmap':
      return `# ${t} — Mind Map

**Subject:** ${s}

## Central Concept: ${t}

### Branch 1: Fundamentals
  - Definition of ${t}
  - Historical background
  - Key terminology
  - Basic principles

### Branch 2: Core Principles
  - Theoretical framework
  - Mathematical foundations
  - Key relationships
  - Governing rules

### Branch 3: Applications
  - Real-world use cases
  - Industry applications
  - Research areas
  - Future directions

### Branch 4: Problem Solving
  - Common problem types
  - Solution strategies
  - Step-by-step methods
  - Practice resources

### Branch 5: Connections
  - Related topics in ${s}
  - Interdisciplinary links
  - Prerequisite knowledge
  - Advanced extensions

## Visual Structure

\`\`\`
          [Fundamentals]
               |
[Principles]—[${t}]—[Applications]
               |
          [Problem Solving]
               |
          [Connections]
\`\`\`

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;

    default: // long notes
      return `# ${t}

**Subject:** ${s}
**Generated:** ${new Date().toLocaleDateString()}

---

## Introduction

${t} is a fundamental topic within ${s}. Understanding its core principles is essential for building a strong foundation in the subject. This comprehensive note covers the key concepts, theories, and applications.

## Core Concepts

### Definition
${t} refers to the set of principles, methods, and theories that form an important area of study in ${s}. It encompasses both theoretical understanding and practical application.

### Key Principles
1. **Principle 1:** The foundational rule governing ${t}
2. **Principle 2:** The relationship between key variables
3. **Principle 3:** The conditions under which ${t} applies

### Important Theories
- **Theory A:** Explains the fundamental mechanism behind ${t}
- **Theory B:** Provides a framework for understanding applications
- **Theory C:** Connects ${t} to broader concepts in ${s}

## Detailed Explanation

The study of ${t} involves understanding several interconnected concepts. At its core, ${t} builds upon basic principles and extends them to solve complex problems. The key is to grasp the fundamental relationships and learn to apply them systematically.

### Step-by-Step Process
1. **Identify** the problem context
2. **Recall** relevant principles of ${t}
3. **Apply** the appropriate methods
4. **Verify** the solution makes sense
5. **Reflect** on what was learned

## Applications

### Real-World Examples
- **Example 1:** How ${t} is used in industry
- **Example 2:** Research applications of ${t}
- **Example 3:** Everyday scenarios involving ${t}

### Practice Problems
1. **Basic:** Apply the definition of ${t} to a simple scenario
2. **Intermediate:** Solve a problem using multiple principles
3. **Advanced:** Analyze a complex case study involving ${t}

## Summary

${t} is a crucial topic in ${s} that requires both theoretical understanding and practical skills. By mastering the core concepts, practicing regularly, and connecting ideas, you can build a strong foundation for advanced study.

## Further Reading
- Textbook chapters related to ${t}
- Research papers on recent developments
- Online resources and video tutorials

---

*Generated by AI StudyMate • ${new Date().toLocaleDateString()}*`;
  }
}

function formatNoteContent(content: string): string {
  return content
    .replace(/```(\w*)\n([\s\S]*?)```/g, (_, lang, code) => `<pre class="code-block my-3"><code>${code.trim()}</code></pre>`)
    .replace(/\*\*(.*?)\*\*/g, '<strong class="text-white font-semibold">$1</strong>')
    .replace(/^# (.*)/gm, '<h1 class="text-xl font-bold text-white mt-4 mb-3">$1</h1>')
    .replace(/^## (.*)/gm, '<h2 class="text-lg font-bold text-white mt-4 mb-2">$1</h2>')
    .replace(/^### (.*)/gm, '<h3 class="text-base font-semibold text-white mt-3 mb-1.5">$1</h3>')
    .replace(/^> (.*)/gm, '<blockquote class="border-l-2 border-blue-500 pl-3 my-2 text-slate-400 italic">$1</blockquote>')
    .replace(/^- \*\*(.*?)\*\*:(.*?)$/gm, '<li class="ml-5 text-slate-300 text-sm list-disc"><strong class="text-white">$1</strong>:$2</li>')
    .replace(/^- (.*)/gm, '<li class="ml-5 text-slate-300 text-sm list-disc">$1</li>')
    .replace(/^[0-9]+\. (.*)/gm, '<li class="ml-5 text-slate-300 text-sm list-decimal">$1</li>')
    .replace(/^---$/gm, '<hr class="border-white/10 my-4"/>')
    .replace(/\| (.*?) \|/g, '<span class="inline-block px-2 py-0.5 bg-white/5 rounded text-xs text-slate-400">$1</span>')
    .replace(/\n\n/g, '</p><p class="mt-3 text-slate-300 text-sm leading-relaxed">')
    .replace(/\n/g, '<br/>');
}

function NoteCard({ note, onDelete, onToggleFavorite, onTogglePin, onSelect }: {
  note: Note;
  onDelete: (id: string) => void;
  onToggleFavorite: (id: string, val: boolean) => void;
  onTogglePin: (id: string, val: boolean) => void;
  onSelect: (note: Note) => void;
}) {
  return (
    <motion.div
      layout
      initial={{ opacity: 0, scale: 0.95 }}
      animate={{ opacity: 1, scale: 1 }}
      exit={{ opacity: 0, scale: 0.95 }}
      className="glass-card p-5 cursor-pointer transition-all duration-300 group flex flex-col gap-3"
      onClick={() => onSelect(note)}
      style={{ background: 'rgba(255,255,255,0.05)' }}
    >
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2 min-w-0">
          {note.is_pinned && <Pin className="w-3.5 h-3.5 text-amber-400 flex-shrink-0" />}
          <h3 className="text-sm font-semibold text-white truncate">{note.title}</h3>
        </div>
        <div className="flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-all">
          <button onClick={e => { e.stopPropagation(); onToggleFavorite(note.id, !note.is_favorite); }}
            className={`p-1.5 rounded-lg transition-all ${note.is_favorite ? 'text-yellow-400 bg-yellow-500/10' : 'text-slate-500 hover:text-yellow-400'}`}>
            <Star className="w-3.5 h-3.5" />
          </button>
          <button onClick={e => { e.stopPropagation(); onTogglePin(note.id, !note.is_pinned); }}
            className={`p-1.5 rounded-lg transition-all ${note.is_pinned ? 'text-amber-400 bg-amber-500/10' : 'text-slate-500 hover:text-amber-400'}`}>
            <Pin className="w-3.5 h-3.5" />
          </button>
          <button onClick={e => { e.stopPropagation(); onDelete(note.id); }}
            className="p-1.5 rounded-lg text-slate-500 hover:text-red-400 hover:bg-red-500/10 transition-all">
            <Trash2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>

      <p className="text-xs text-slate-400 line-clamp-3 leading-relaxed">
        {note.content?.replace(/[#*`|]/g, '').replace(/---/g, '').slice(0, 150) ?? 'No content'}
      </p>

      <div className="flex items-center justify-between pt-1">
        <div className="flex items-center gap-2">
          {note.subject && (
            <span className="badge bg-blue-600/20 text-blue-300 border border-blue-500/20 text-xs">{note.subject}</span>
          )}
          <span className="badge bg-white/5 text-slate-500 text-xs capitalize">{note.note_type}</span>
        </div>
        <span className="text-xs text-slate-600">{new Date(note.created_at).toLocaleDateString()}</span>
      </div>
    </motion.div>
  );
}

export default function NotesGenerator() {
  const [notes, setNotes] = useState<Note[]>([]);
  const [selectedNote, setSelectedNote] = useState<Note | null>(null);
  const [showCreate, setShowCreate] = useState(false);
  const [generating, setGenerating] = useState(false);
  const [saving, setSaving] = useState(false);
  const [generateError, setGenerateError] = useState('');
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const [filterSubject, setFilterSubject] = useState('');
  const [loading, setLoading] = useState(true);

  const [form, setForm] = useState({
    title: '',
    topic: '',
    subject: '',
    note_type: 'long',
    source_type: 'manual',
    source_url: '',
    content: '',
    tags: [] as string[],
    tagInput: '',
  });

  useEffect(() => {
    loadNotes();
  }, []);

  const loadNotes = async () => {
    const { data, error } = await supabase
      .from('notes')
      .select('*')
      .order('is_pinned', { ascending: false })
      .order('created_at', { ascending: false });
    if (!error) setNotes(data ?? []);
    setLoading(false);
  };

  const generateNotes = async () => {
    if (!form.title.trim() && !form.topic.trim()) {
      setGenerateError('Please enter a title or topic to generate notes.');
      return;
    }
    setGenerateError('');
    setGenerating(true);
    try {
      await new Promise(r => setTimeout(r, 1500));
      const topic = form.topic.trim() || form.title.trim();
      const content = generateNoteContent(topic, form.note_type, form.subject);
      setForm(f => ({ ...f, content, title: f.title || topic }));
    } catch {
      setGenerateError('Failed to generate notes. Please try again.');
    } finally {
      setGenerating(false);
    }
  };

  const saveNote = async () => {
    if (!form.title.trim()) {
      setGenerateError('Please enter a note title before saving.');
      return;
    }
    if (!form.content.trim()) {
      setGenerateError('Please generate or write note content before saving.');
      return;
    }
    setGenerateError('');
    setSaving(true);
    try {
      const { data, error } = await supabase.from('notes').insert({
        title: form.title,
        content: form.content,
        note_type: form.note_type,
        subject: form.subject || null,
        tags: form.tags,
        source_type: form.source_type,
        source_url: form.source_url || null,
      }).select().single();
      if (error) throw error;
      if (data) {
        setNotes(prev => [data, ...prev]);
        setSaveSuccess(true);
        setTimeout(() => {
          setShowCreate(false);
          setSaveSuccess(false);
          setForm({ title: '', topic: '', subject: '', note_type: 'long', source_type: 'manual', source_url: '', content: '', tags: [], tagInput: '' });
        }, 1000);
      }
    } catch {
      setGenerateError('Failed to save note. Please try again.');
    } finally {
      setSaving(false);
    }
  };

  const deleteNote = async (id: string) => {
    const { error } = await supabase.from('notes').delete().eq('id', id);
    if (!error) {
      setNotes(prev => prev.filter(n => n.id !== id));
      if (selectedNote?.id === id) setSelectedNote(null);
    }
  };

  const toggleFavorite = async (id: string, val: boolean) => {
    await supabase.from('notes').update({ is_favorite: val }).eq('id', id);
    setNotes(prev => prev.map(n => n.id === id ? { ...n, is_favorite: val } : n));
  };

  const togglePin = async (id: string, val: boolean) => {
    await supabase.from('notes').update({ is_pinned: val }).eq('id', id);
    setNotes(prev => {
      const updated = prev.map(n => n.id === id ? { ...n, is_pinned: val } : n);
      return [...updated.filter(n => n.is_pinned), ...updated.filter(n => !n.is_pinned)];
    });
  };

  const addTag = () => {
    if (form.tagInput.trim() && !form.tags.includes(form.tagInput.trim())) {
      setForm(f => ({ ...f, tags: [...f.tags, f.tagInput.trim()], tagInput: '' }));
    }
  };

  const filtered = notes.filter(n => {
    const q = searchQuery.toLowerCase();
    const matchSearch = !q || n.title.toLowerCase().includes(q) || n.content?.toLowerCase().includes(q) || n.subject?.toLowerCase().includes(q);
    const matchSubject = !filterSubject || n.subject === filterSubject;
    return matchSearch && matchSubject;
  });

  return (
    <div className="flex h-[calc(100vh-120px)] gap-4">
      {/* Notes List */}
      <div className={`flex flex-col gap-4 ${selectedNote ? 'w-[380px] flex-shrink-0' : 'flex-1'}`}>
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h2 className="text-xl font-bold text-white">My Notes</h2>
            <p className="text-xs text-slate-500">{notes.length} notes total</p>
          </div>
          <button onClick={() => setShowCreate(true)} className="btn-primary text-sm py-2">
            <Plus className="w-4 h-4" />
            New Note
          </button>
        </div>

        {/* Filters */}
        <div className="flex gap-2">
          <div className="relative flex-1">
            <Search className="absolute left-3 top-2.5 w-3.5 h-3.5 text-slate-500" />
            <input
              placeholder="Search notes..."
              value={searchQuery}
              onChange={e => setSearchQuery(e.target.value)}
              className="input-field pl-9 py-2 text-sm"
            />
          </div>
          <select
            value={filterSubject}
            onChange={e => setFilterSubject(e.target.value)}
            className="input-field py-2 text-sm w-40"
          >
            <option value="">All Subjects</option>
            {SUBJECTS.map(s => <option key={s} value={s}>{s}</option>)}
          </select>
        </div>

        {/* Notes Grid */}
        <div className="flex-1 overflow-y-auto">
          {loading ? (
            <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
              {[1,2,3,4].map(i => <div key={i} className="h-40 glass-card shimmer" />)}
            </div>
          ) : filtered.length === 0 ? (
            <div className="flex flex-col items-center justify-center py-16 text-center">
              <BookOpen className="w-12 h-12 text-slate-700 mb-3" />
              <p className="text-slate-400 font-medium">No notes yet</p>
              <p className="text-sm text-slate-600 mb-4">Create your first AI-generated note</p>
              <button onClick={() => setShowCreate(true)} className="btn-primary text-sm">
                <Wand2 className="w-4 h-4" />
                Generate with AI
              </button>
            </div>
          ) : (
            <div className={`grid gap-3 ${selectedNote ? 'grid-cols-1' : 'grid-cols-1 md:grid-cols-2 lg:grid-cols-3'}`}>
              <AnimatePresence>
                {filtered.map(note => (
                  <NoteCard
                    key={note.id}
                    note={note}
                    onDelete={deleteNote}
                    onToggleFavorite={toggleFavorite}
                    onTogglePin={togglePin}
                    onSelect={setSelectedNote}
                  />
                ))}
              </AnimatePresence>
            </div>
          )}
        </div>
      </div>

      {/* Note Viewer */}
      <AnimatePresence>
        {selectedNote && (
          <motion.div
            initial={{ opacity: 0, x: 20 }}
            animate={{ opacity: 1, x: 0 }}
            exit={{ opacity: 0, x: 20 }}
            className="flex-1 glass-card flex flex-col min-w-0"
          >
            <div className="flex items-center justify-between p-5 border-b border-white/10">
              <div className="flex-1 min-w-0">
                <h2 className="font-bold text-white text-lg truncate">{selectedNote.title}</h2>
                <div className="flex items-center gap-2 mt-1">
                  {selectedNote.subject && <span className="badge bg-blue-600/20 text-blue-300 border border-blue-500/20">{selectedNote.subject}</span>}
                  <span className="badge bg-white/5 text-slate-500 capitalize">{selectedNote.note_type}</span>
                </div>
              </div>
              <div className="flex items-center gap-2">
                <button onClick={() => navigator.clipboard.writeText(selectedNote.content ?? '')} className="btn-ghost p-2" title="Copy">
                  <Copy className="w-4 h-4" />
                </button>
                <button className="btn-ghost p-2" title="Download">
                  <Download className="w-4 h-4" />
                </button>
                <button onClick={() => setSelectedNote(null)} className="btn-ghost p-2" title="Close">
                  <X className="w-4 h-4" />
                </button>
              </div>
            </div>
            <div className="flex-1 overflow-y-auto p-6">
              <div
                className="max-w-none"
                dangerouslySetInnerHTML={{ __html: `<p class="text-slate-300 text-sm leading-relaxed">${formatNoteContent(selectedNote.content ?? '')}</p>` }}
              />
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Create Note Modal */}
      <AnimatePresence>
        {showCreate && (
          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            exit={{ opacity: 0 }}
            className="fixed inset-0 z-50 bg-black/60 backdrop-blur-sm flex items-center justify-center p-4"
            onClick={e => { if (e.target === e.currentTarget) setShowCreate(false); }}
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              exit={{ opacity: 0, scale: 0.95 }}
              className="w-full max-w-2xl glass-card p-6 max-h-[90vh] overflow-y-auto"
            >
              <div className="flex items-center justify-between mb-6">
                <div className="flex items-center gap-3">
                  <div className="p-2 bg-blue-600/20 rounded-xl">
                    <Wand2 className="w-5 h-5 text-blue-400" />
                  </div>
                  <h3 className="text-lg font-bold text-white">Create AI Note</h3>
                </div>
                <button onClick={() => setShowCreate(false)} className="btn-ghost p-2">
                  <X className="w-4 h-4" />
                </button>
              </div>

              {/* Error message */}
              {generateError && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex items-center gap-2 p-3 mb-4 bg-red-500/10 border border-red-500/30 rounded-xl text-red-400 text-sm"
                >
                  <AlertCircle className="w-4 h-4 flex-shrink-0" />
                  {generateError}
                </motion.div>
              )}

              {/* Success message */}
              {saveSuccess && (
                <motion.div
                  initial={{ opacity: 0, y: -10 }}
                  animate={{ opacity: 1, y: 0 }}
                  className="flex items-center gap-2 p-3 mb-4 bg-green-500/10 border border-green-500/30 rounded-xl text-green-400 text-sm"
                >
                  <Check className="w-4 h-4 flex-shrink-0" />
                  Note saved successfully!
                </motion.div>
              )}

              <div className="space-y-4">
                <div className="grid grid-cols-2 gap-3">
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">Note Title *</label>
                    <input
                      value={form.title}
                      onChange={e => setForm(f => ({ ...f, title: e.target.value }))}
                      placeholder="e.g., Machine Learning Notes"
                      className="input-field"
                    />
                  </div>
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">Subject</label>
                    <select value={form.subject} onChange={e => setForm(f => ({ ...f, subject: e.target.value }))} className="input-field">
                      <option value="">Select subject</option>
                      {SUBJECTS.map(s => <option key={s} value={s}>{s}</option>)}
                    </select>
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">Note Type</label>
                  <div className="grid grid-cols-4 gap-2">
                    {NOTE_TYPES.map(t => (
                      <button
                        key={t.value}
                        onClick={() => setForm(f => ({ ...f, note_type: t.value }))}
                        className={`p-2.5 rounded-xl border text-xs font-medium transition-all ${
                          form.note_type === t.value
                            ? 'bg-blue-600/20 border-blue-500/50 text-blue-300'
                            : 'bg-white/5 border-white/10 text-slate-400 hover:border-white/20'
                        }`}
                      >
                        {t.label}
                      </button>
                    ))}
                  </div>
                </div>

                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">Source</label>
                  <div className="grid grid-cols-5 gap-2">
                    {SOURCE_TYPES.map(s => (
                      <button
                        key={s.value}
                        onClick={() => setForm(f => ({ ...f, source_type: s.value }))}
                        className={`flex flex-col items-center gap-1.5 p-2.5 rounded-xl border text-xs transition-all ${
                          form.source_type === s.value
                            ? 'bg-blue-600/20 border-blue-500/50 text-blue-300'
                            : 'bg-white/5 border-white/10 text-slate-400 hover:border-white/20'
                        }`}
                      >
                        <s.icon className="w-4 h-4" />
                        {s.label}
                      </button>
                    ))}
                  </div>
                </div>

                {form.source_type === 'manual' ? (
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">Topic / Content</label>
                    <textarea
                      value={form.topic}
                      onChange={e => setForm(f => ({ ...f, topic: e.target.value }))}
                      placeholder="Enter a topic (e.g., Neural Networks) or paste content for AI to generate notes from..."
                      rows={3}
                      className="input-field resize-none"
                    />
                  </div>
                ) : (
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">
                      {form.source_type === 'youtube' ? 'YouTube URL' : form.source_type === 'website' ? 'Website URL' : 'Upload File'}
                    </label>
                    <input
                      value={form.source_url}
                      onChange={e => setForm(f => ({ ...f, source_url: e.target.value, topic: e.target.value }))}
                      placeholder={form.source_type === 'youtube' ? 'https://youtube.com/watch?v=...' : 'https://...'}
                      className="input-field"
                    />
                  </div>
                )}

                {/* Generated content preview */}
                {form.content && (
                  <div>
                    <label className="block text-sm font-medium text-slate-300 mb-2">Generated Content Preview</label>
                    <div className="glass-card p-4 max-h-48 overflow-y-auto">
                      <div
                        dangerouslySetInnerHTML={{ __html: `<p class="text-slate-300 text-sm leading-relaxed">${formatNoteContent(form.content)}</p>` }}
                      />
                    </div>
                  </div>
                )}

                {/* Tags */}
                <div>
                  <label className="block text-sm font-medium text-slate-300 mb-2">Tags</label>
                  <div className="flex gap-2">
                    <input
                      value={form.tagInput}
                      onChange={e => setForm(f => ({ ...f, tagInput: e.target.value }))}
                      onKeyDown={e => e.key === 'Enter' && (e.preventDefault(), addTag())}
                      placeholder="Add tag..."
                      className="input-field flex-1 py-2"
                    />
                    <button onClick={addTag} className="btn-secondary px-3 py-2">
                      <Plus className="w-4 h-4" />
                    </button>
                  </div>
                  {form.tags.length > 0 && (
                    <div className="flex flex-wrap gap-1.5 mt-2">
                      {form.tags.map(tag => (
                        <span key={tag} className="flex items-center gap-1 badge bg-white/10 text-slate-300 border border-white/15">
                          <Tag className="w-2.5 h-2.5" />
                          {tag}
                          <button onClick={() => setForm(f => ({ ...f, tags: f.tags.filter(t => t !== tag) }))}>
                            <X className="w-2.5 h-2.5 text-slate-500 hover:text-white" />
                          </button>
                        </span>
                      ))}
                    </div>
                  )}
                </div>

                <div className="flex gap-3 pt-2">
                  <button
                    onClick={generateNotes}
                    disabled={generating || (!form.title.trim() && !form.topic.trim())}
                    className="btn-secondary flex-1"
                  >
                    {generating ? (
                      <><Loader2 className="w-4 h-4 animate-spin" /> Generating...</>
                    ) : (
                      <><Sparkles className="w-4 h-4 text-blue-400" /> Generate with AI</>
                    )}
                  </button>
                  <button
                    onClick={saveNote}
                    disabled={saving || !form.title.trim() || !form.content.trim()}
                    className="btn-primary flex-1"
                  >
                    {saving ? (
                      <><Loader2 className="w-4 h-4 animate-spin" /> Saving...</>
                    ) : (
                      <><Check className="w-4 h-4" /> Save Note</>
                    )}
                  </button>
                </div>
              </div>
            </motion.div>
          </motion.div>
        )}
      </AnimatePresence>
    </div>
  );
}
